version: "3.9"

services:
  gateway:
    container_name: gateway
    image: tiny-chat-gateway:latest
    volumes:
      - ./gateway/configs:/data/conf
    ports:
      - "8081:8081"
    depends_on:
      - auth
      - messenger
    networks:
      tiny-chat-network:
        ipv4_address: 172.21.0.10

  auth:
    container_name: auth
    image: tiny-chat-auth:latest
    volumes:
      - ./auth/configs:/data/conf
    ports:
      - "8000:8000"
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      tiny-chat-network:
        ipv4_address: 172.21.0.11

  messenger:
    container_name: messenger
    image: tiny-chat-messenger:latest
    restart: always
    volumes:
      - ./messenger/configs:/data/conf
    ports:
      - "8001:8000"
      - "9001:9000"
    depends_on:
      - postgres
      - broker
    networks:
      tiny-chat-network:
        ipv4_address: 172.21.0.12

  broker:
    image: confluentinc/cp-kafka:7.1.1
    container_name: broker
    ports:
      - "9092:9092"
      - "9101:9101"
    expose:
      - "29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./kafka/update_run.sh:/tmp/update_run.sh
    command: "bash -c 'if [ ! -f /tmp/update_run.sh ]; then echo \"ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/update_run.sh && /etc/confluent/docker/run ; fi'"
    networks:
      tiny-chat-network:
        ipv4_address: 172.21.0.50

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - /var/run/postgresql:/var/run/postgresql
    environment:
      POSTGRES_DB: tiny_chat
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      tiny-chat-network:
        ipv4_address: 172.21.0.32

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.35
    ports:
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
    networks:
      tiny-chat-network:
        ipv4_address: 172.21.0.20

  prometheus:
    image: prom/prometheus:v2.36.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      tiny-chat-network:
        ipv4_address: 172.21.0.21

  grafana:
    container_name: grafana
    image: grafana/grafana:8.5.5
    volumes:
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    networks:
      tiny-chat-network:
        ipv4_address: 172.21.0.22

networks:
  tiny-chat-network:
    name: tiny-chat-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1