// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"auth/internal/biz"
	"auth/internal/conf"
	"auth/internal/data"
	"auth/internal/pkg/hash"
	"auth/internal/pkg/paseto"
	"auth/internal/server"
	"auth/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, hasher *conf.Hasher, tokenMaker *conf.TokenMaker, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewGreeterRepo(dataData, logger)
	passwordHasher := hash.NewPasswordHasher(hasher)
	pasetoTokenMaker, err := paseto.NewPasetoMaker(tokenMaker)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	authUsecase := biz.NewAuthUsecase(userRepo, logger, passwordHasher, pasetoTokenMaker)
	authService := service.NewGreeterService(authUsecase)
	grpcServer := server.NewGRPCServer(confServer, authService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
