server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    source: "${DATABASE_SOURCE:}"
hasher:
  salt: "${HASHER_SALT:}"
tokenMaker:
  accessKey: "${TOKEN_MAKER_ACCESS:}"
  accessTtl: 900s
  refreshKey: "${TOKEN_MAKER_REFRESH:}"
  refreshTtl: 86400s
  assert: "${TOKEN_MAKER_ASSERT:}"
tracing:
  url: "http://${JAEGER_HOST:jaeger-collector.tiny-chat.svc.cluster.local}:14268/api/traces"