server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:900
    timeout: 1s
data:
  database:
    driver: postgres
    source: "host=127.0.0.1 user=postgres dbname=auth_test password=12345 sslmode=disable"
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
kafka:
  addr:
  topic:
  groupId:
tracing:
  url:
