server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    source: "host=postgres user=user dbname=tiny_chat password=password sslmode=disable"
kafka:
  addr:
  topic:
  groupId:
tracing:
  url: http://jaeger:14268/api/traces
