global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth'
    scrape_interval: 5s
    static_configs:
      - targets: ['auth:8000']

  - job_name: 'messenger'
    scrape_interval: 5s
    static_configs:
      - targets: ['messenger:8000']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']