// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gusarow4321/TinyChat/pkg/ent/predicate"
	"github.com/gusarow4321/TinyChat/pkg/ent/usermetadata"
)

// UserMetadataDelete is the builder for deleting a UserMetadata entity.
type UserMetadataDelete struct {
	config
	hooks    []Hook
	mutation *UserMetadataMutation
}

// Where appends a list predicates to the UserMetadataDelete builder.
func (umd *UserMetadataDelete) Where(ps ...predicate.UserMetadata) *UserMetadataDelete {
	umd.mutation.Where(ps...)
	return umd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (umd *UserMetadataDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(umd.hooks) == 0 {
		affected, err = umd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserMetadataMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			umd.mutation = mutation
			affected, err = umd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(umd.hooks) - 1; i >= 0; i-- {
			if umd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = umd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, umd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (umd *UserMetadataDelete) ExecX(ctx context.Context) int {
	n, err := umd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (umd *UserMetadataDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: usermetadata.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: usermetadata.FieldID,
			},
		},
	}
	if ps := umd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, umd.driver, _spec)
}

// UserMetadataDeleteOne is the builder for deleting a single UserMetadata entity.
type UserMetadataDeleteOne struct {
	umd *UserMetadataDelete
}

// Exec executes the deletion query.
func (umdo *UserMetadataDeleteOne) Exec(ctx context.Context) error {
	n, err := umdo.umd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usermetadata.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (umdo *UserMetadataDeleteOne) ExecX(ctx context.Context) {
	umdo.umd.ExecX(ctx)
}
