apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-chart.fullname" . }}
type: Opaque
stringData:
  salt: {{ .Values.secret.salt }}
  access: {{ .Values.secret.access }}
  refresh: {{ .Values.secret.refresh }}
  assert: {{ .Values.secret.assert }}