apiVersion: v1
kind: Service
metadata:
  name: {{ include "messenger-chart.fullname" . }}
  labels:
    {{- include "messenger-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "messenger-chart.selectorLabels" . | nindent 4 }}
