server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    source: "${DATABASE_SOURCE:}"
kafka:
  addr: "${KAFKA_HOST:kafka.tiny-chat.svc.cluster.local}:9092"
  topic: messages
  groupId: messenger
tracing:
  url: "http://${JAEGER_HOST:jaeger-collector.tiny-chat.svc.cluster.local}:14268/api/traces"