// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package tests

import (
	"github.com/go-kratos/kratos/v2/log"
	"github.com/gusarow4321/TinyChat/messenger/internal/biz"
	"github.com/gusarow4321/TinyChat/messenger/internal/pkg/kafka"
	"github.com/gusarow4321/TinyChat/messenger/internal/pkg/observer"
	"github.com/gusarow4321/TinyChat/messenger/internal/service"
)

// Injectors from wire.go:

func wireService(messagesProducer kafka.MessagesProducer, messengerRepo biz.MessengerRepo, chatsObserver observer.ChatsObserver, logger log.Logger) (*service.MessengerService, error) {
	messengerUsecase := biz.NewMessengerUsecase(messengerRepo, logger, chatsObserver)
	messengerService := service.NewMessengerService(messengerUsecase, messagesProducer)
	return messengerService, nil
}
